sudo: required
dist: trusty
language: node_js
vm:
  size: large
node_js:
  - 14.18.3
before_script:
  - npm install -g @marp-team/marp-cli
script: 
  - mkdir public
  - cp -r images public/
  - marp innersource.md --allow-local-files --html -o public/index.html
  - marp innersource.md --allow-local-files --html -o public/slides.pdf
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_url: github.com
  target_branch: gh-pages
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: main
